#!/bin/bash

# Parse the command line from gprbuild for the linker

directory=""
out_file=""

OPTIND=2 # Ignore the file name given as the first argument
while getopts ":d:o:" opt ; do
    case $opt in
	d)
	    directory="${OPTARG}/"
	    ;;
	o)
	    out_file="${OPTARG}"
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument" >&2
	    exit 1
	    ;;
	\?)
	    echo "Invalid option -$OPTARG" >&2
	    exit 1
	    ;;
    esac
done

if [[ out_file != "" ]] ; then
   full_out_file="${directory}${out_file}.out"
   else
       full_out_file=""
fi

input_files=${directory}*.json_symtab
symtab2gb ${input_files} --out ${full_out_file}
