#!/bin/bash

# Parse the command line from gprbuild for the linker

# gprbuild assumes the files to be linked are in the directory
# specified as the Object_Dir specified in the gpr file

input_files="*.json_symtab"
out_file=""

OPTIND=2 # Ignore the file name given as the first argument
while getopts ":d:o:" opt ; do
    case $opt in
	o)
	    out_file="${OPTARG}"
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument" >&2
	    exit 1
	    ;;
	\?)
	    echo "Invalid option -$OPTARG" >&2
	    exit 1
	    ;;
    esac
done

if [[ ${out_file} != "" ]] ; then
    out_file_name=$(basename "$out_file")
    echo out_file_name $out_file_name
    out_ext="${out_file_name##*.}"
    echo out_ext $out_ext
    if [[ ${out_ext} == "" ]] || [[ ${out_ext} == ${out_file_name} ]] ; then
	full_out_file="--out ${out_file_name}.out"
    else
	full_out_file="--out ${out_file_name}"
    fi
else
       full_out_file=""
fi

echo symtab2gb ${input_files} ${full_out_file}
symtab2gb ${input_files} ${full_out_file}
